### ISSUE TITLE
Update gitignore

### ISSUE THREAD

**Issue by Magnat12** [dgozhenko/EverydayDiary#4]
*~
.DS_Store
*.mode1
*.mode1v3
*.mode2v3
*.perspective
*.perspectivev3
*.ipa
*.DSYM.zip

# Xcode
*.xcuserdata
*.pbxuser 
*.xccheckout 
*.moved-aside
*.xcscmblueprint
*.xcuserstate
*.xcbkptlist
*.xcscheme

# CocoaPods
Pods

# Fastlane
*/fastlnae/builds
*/fastlane/report.xml
*/fastlane/Preview.html
*/fastlane/screenshots
*/fastlane/test_output
report.xml
IDEFindNavigatorScopes.plist
xcschememanagement.plist

**Comment by dgozhenko** [comment]
Added
